"""
Audio serving endpoint — serves pre-generated ElevenLabs MP3 files
to telephony providers (Twilio, Exotel) during live calls.

GET /api/v1/audio/{token}

The token is generated by tts_service._make_token() during campaign preparation.
No authentication required — the token itself is the secret (HMAC-signed, time-windowed).
This endpoint MUST be publicly reachable by Twilio/Exotel servers.
"""
from __future__ import annotations

from fastapi import APIRouter, HTTPException, status
from fastapi.responses import Response

from app.services.tts_service import get_cached_audio

router = APIRouter()


@router.get("/audio/{token}")
async def serve_audio(token: str):
    """
    Serve pre-generated TTS audio for a telephony call.

    Called by Twilio/Exotel during the live call when the flow engine
    instructs Play(audio_url=...). Returns MP3 bytes.

    Token is time-windowed (24h) and HMAC-signed — safe to expose publicly.
    """
    audio = get_cached_audio(token)
    if audio is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Audio not found or expired. Regenerate campaign audio.",
        )
    return Response(
        content=audio,
        media_type="audio/mpeg",
        headers={
            "Cache-Control": "public, max-age=86400",
            "Content-Length": str(len(audio)),
        },
    )
