"""Initial migration

Revision ID: e90e4907f2e6
Revises: 
Create Date: 2026-10-09 15:41:58.052730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e90e4907f2e6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_enc', sa.LargeBinary(), nullable=False),
    sa.Column('phone_hash', sa.String(length=64), nullable=False),
    sa.Column('phone_last4', sa.String(length=4), nullable=False),
    sa.Column('name_enc', sa.LargeBinary(), nullable=True),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('segment', sa.Text(), nullable=True),
    sa.Column('consent', sa.Boolean(), nullable=False),
    sa.Column('consent_source', sa.Text(), nullable=True),
    sa.Column('consent_at', sa.DateTime(), nullable=True),
    sa.Column('dnd', sa.Boolean(), nullable=False),
    sa.Column('opted_out', sa.Boolean(), nullable=False),
    sa.Column('opted_out_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_hash')
    )
    op.create_table('dnd_numbers',
    sa.Column('phone_hash', sa.String(length=64), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('phone_hash')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("role IN ('admin','organiser')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('object_type', sa.Text(), nullable=False),
    sa.Column('object_id', sa.Text(), nullable=False),
    sa.Column('ip', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('use_case', sa.Text(), nullable=False),
    sa.Column('source_language', sa.String(length=2), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('script', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dtmf_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('speech_enabled', sa.Boolean(), nullable=False),
    sa.Column('voicemail_policy', sa.Text(), nullable=False),
    sa.Column('is_preset', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("use_case IN ('seminar','clinic','school','payment','custom')", name='ck_templates_use_case'),
    sa.CheckConstraint("voicemail_policy IN ('leave_message','skip_and_retry')", name='ck_templates_voicemail_policy'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('event_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('variable_overrides', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('languages', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('caller_id', sa.Text(), nullable=True),
    sa.Column('calling_window_start', sa.Time(), nullable=False),
    sa.Column('calling_window_end', sa.Time(), nullable=False),
    sa.Column('timezone', sa.Text(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('max_concurrent_calls', sa.Integer(), nullable=False),
    sa.Column('retry_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('speech_confidence_threshold', sa.Float(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('launched_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('draft','preparing','needs_review','ready','running','paused','completed','cancelled')", name='ck_campaigns_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_translations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("source IN ('ai','manual')", name='ck_translations_source'),
    sa.CheckConstraint("status IN ('draft','approved')", name='ck_translations_status'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'language', name='uq_template_translations_lang')
    )
    op.create_table('audio_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('segment_key', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('wav_path', sa.Text(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'language', 'segment_key', name='uq_audio_assets_key')
    )
    op.create_table('campaign_contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('segment', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts_override', sa.Integer(), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('last_outcome', sa.Text(), nullable=True),
    sa.Column('final_outcome', sa.Text(), nullable=True),
    sa.Column('last_call_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("state IN ('pending','in_call','waiting_retry','done','exhausted','skipped')", name='ck_campaign_contacts_state'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'contact_id', name='uq_campaign_contacts_pair')
    )
    op.create_index('ix_campaign_contacts_dispatch', 'campaign_contacts', ['campaign_id', 'state', 'next_attempt_at'], unique=False)
    op.create_table('calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_contact_id', sa.UUID(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('provider_call_sid', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('amd_result', sa.Text(), nullable=True),
    sa.Column('flow_step', sa.Text(), nullable=True),
    sa.Column('flow_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('hangup_cause', sa.Text(), nullable=True),
    sa.Column('recording_path', sa.Text(), nullable=True),
    sa.Column('recording_provider_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("amd_result IN ('human','machine','unknown') OR amd_result IS NULL", name='ck_calls_amd_result'),
    sa.CheckConstraint("provider IN ('exotel','mock')", name='ck_calls_provider'),
    sa.CheckConstraint("status IN ('initiated','ringing','in_progress','completed','failed','busy','no_answer','canceled')", name='ck_calls_status'),
    sa.ForeignKeyConstraint(['campaign_contact_id'], ['campaign_contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_call_sid')
    )
    op.create_index('ix_calls_campaign_contact_id', 'calls', ['campaign_contact_id'], unique=False)
    op.create_table('call_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=True),
    sa.Column('provider_call_sid', sa.Text(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_call_events_provider_call_sid', 'call_events', ['provider_call_sid'], unique=False)
    op.create_table('intents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('step_key', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('raw_input', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('stt_model', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("label IN ('confirm','decline','reschedule','call_later','stop_calling','unclear')", name='ck_intents_label'),
    sa.CheckConstraint("source IN ('dtmf','speech')", name='ck_intents_source'),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_intents_call_id', 'intents', ['call_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_intents_call_id', table_name='intents')
    op.drop_table('intents')
    op.drop_index('ix_call_events_provider_call_sid', table_name='call_events')
    op.drop_table('call_events')
    op.drop_index('ix_calls_campaign_contact_id', table_name='calls')
    op.drop_table('calls')
    op.drop_index('ix_campaign_contacts_dispatch', table_name='campaign_contacts')
    op.drop_table('campaign_contacts')
    op.drop_table('audio_assets')
    op.drop_table('template_translations')
    op.drop_table('campaigns')
    op.drop_table('templates')
    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_table('dnd_numbers')
    op.drop_table('contacts')
    # ### end Alembic commands ###
