#!/usr/bin/env bash
# scripts/gen_secrets.sh
# Veylo PR 002 — Generate random secret values for .env
# Usage: bash scripts/gen_secrets.sh
# Copy the output into your .env file.

set -euo pipefail

b64() { python3 -c "import secrets,base64; print(base64.b64encode(secrets.token_bytes(32)).decode())"; }
hex() { python3 -c "import secrets; print(secrets.token_hex(32))"; }
url() { python3 -c "import secrets; print(secrets.token_urlsafe(32))"; }

echo "# Generated by scripts/gen_secrets.sh on $(date)"
echo "# Paste these into your .env file. Keep them secret."
echo ""
echo "JWT_SECRET=$(hex)"
echo "DATA_ENC_KEY=$(b64)"
echo "PHONE_HMAC_KEY=$(b64)"
echo "WEBHOOK_SECRET=$(url)"
echo "AI_INTERNAL_TOKEN=$(url)"
echo "POSTGRES_PASSWORD=$(url)"
echo "REDIS_PASSWORD=$(url)"
echo "ADMIN_PASSWORD=$(url)"
